In [2]:
import numpy as np

#Datatypes and Attributes


In [4]:
a1=np.array([1,2,3])
a1

#creating a one dimensional array

array([1, 2, 3])

In [3]:
type(a1)
#this type function specifies the type of the array.

numpy.ndarray

In [4]:
#the ndarray stands for n dim array..

In [5]:
#let us create a few more arrays with multi dim.
a2=np.array([[1,2,3],
            [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3=np.array([[[1,2,3],
            [3,4,5],],
             
            [[6,7,8],
            [9,10,11]]])
a3


array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [3]:
import pandas as pd

In [10]:
#creating a dataframe using a numpy array.
df=pd.DataFrame(a2)

In [11]:
df

0  1  2
0  1  2  3
1  4  5  6

In [12]:
#to view the dimension of the particular array
a1.ndim

1

In [13]:
#to view the shape of the array
a1.shape

#here there are series of three number so it is displayed as 3 but actually its (1,3) let me show you in 2 dim array.

(3,)

In [14]:
a2.shape
#two rows and three columns so its (2,3)

(2, 3)

##creating numpy arryas.

In [7]:
ones=np.ones((2,3),dtype=np.float64)

#this returns the specific shape we have defined and the default datatype is float.we have changed here to int 

In [24]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
ones.dtype

dtype('float64')

In [26]:
#there is also an interesting thing filling with zeros.

zero=np.zeros((2,3))

In [27]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
zero.dtype

dtype('float64')

In [28]:
# now we are going to see a similar function we came across in python range()

ranges=np.arange(0,10,5)

#the syntax is very common arange(start,stop,step(increment))

In [29]:
ranges

array([0, 5])

In [31]:
#Including random values in the array

random_arr=np.random.randint(0,20,size=(3,3))

#for some clarifications click inside the function bracket and press shift+tab .

In [32]:
random_arr

array([[ 9,  3, 16],
       [ 6,  3, 10],
       [ 5, 14, 10]])

In [34]:
#well thats not what we expected right the problem is we need to declare the shape(mentioned as size in the function)of the array

random_arr1=np.random.randint(1,20,size=(2,3))

In [35]:
random_arr1

array([[ 3, 12, 15],
       [10,  5, 12]])

In [37]:
random_arr1.size,random_arr1.ndim

#the answer would be (size of the array , dimension of the array)

(6, 2)

In [38]:
random_arr1.shape

(2, 3)

In [39]:
random_arr2=np.random.random(size=(3,3))

#this returns complete random float values
random_arr2

array([[0.36175532, 0.69327589, 0.44449266],
       [0.05833191, 0.75219473, 0.16513367],
       [0.48482282, 0.37229562, 0.14559128]])

In [40]:
#here we'll see another similar type to random.random()

random_arr3=np.random.rand(10,10)

random_arr3 #the shape of the array is 10x10

array([[0.13713707, 0.67282053, 0.90834522, 0.26637889, 0.21537837,
        0.39481695, 0.85095473, 0.5607777 , 0.09517721, 0.3065927 ],
       [0.26222453, 0.86654907, 0.55969837, 0.31284682, 0.05657131,
        0.86662823, 0.79271605, 0.8340657 , 0.62872591, 0.90456562],
       [0.26928852, 0.71233011, 0.19287442, 0.60205473, 0.76217138,
        0.1202064 , 0.26980471, 0.60770251, 0.6208256 , 0.36658273],
       [0.43420983, 0.72502486, 0.76965473, 0.89249417, 0.43772238,
        0.66984587, 0.12156087, 0.47457727, 0.25781903, 0.15873748],
       [0.49301263, 0.29185095, 0.84298277, 0.24075794, 0.80545446,
        0.19936507, 0.08738979, 0.70155087, 0.48783279, 0.38363505],
       [0.86415616, 0.99580281, 0.90132908, 0.74182529, 0.27731944,
        0.8727227 , 0.28670863, 0.25991193, 0.13014158, 0.07142464],
       [0.28220663, 0.2999736 , 0.55224743, 0.1918817 , 0.11624508,
        0.79542003, 0.91452522, 0.37411839, 0.54001107, 0.90334437],
       [0.75899109, 0.71860215, 0.6342853

# Random Seed

In [41]:
# here we'll look after one of the most important function in random which is random seed 

random_array_1=np.random.randint(0,9,size=(2,3))

random_array_1

#Run this line multiple times you will notice that the values get's changed every single time we run it

array([[6, 6, 1],
       [3, 2, 7]])

In [44]:
#so to fix this changing values we need to use random.seed() this function will prevent from changes.
np.random.seed(seed=7)
random_array_3=np.random.random((2,3))
 
random_array_3

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587]])

# view the arrays

In [45]:
a1

array([1, 2, 3])

In [46]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a3

#you can view array like this jus kidding in here we'll see about 
# 1.unique
# 2.viewing by index position
# 3.slicing operator

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [48]:
np.unique(a1)

array([1, 2, 3])

In [49]:
np.unique(a2)

#this returns unique values in the array

array([1, 2, 3, 4, 5, 6])

In [50]:
np.unique(a3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [56]:
# here we can we the data by index position 

a3[0]




array([[1, 2, 3],
       [3, 4, 5]])

In [57]:
a3.shape,a3.ndim


((2, 2, 3), 3)

In [64]:
#let us create an arrya of 3 dimension

a4=np.random.randint(20,size=(2,3,4,4))

#here inside the size (2-times,3-dimensions,4-rows,4-columns)

In [65]:
a4

array([[[[ 9, 12,  3, 14],
         [14, 15,  3, 16],
         [ 4, 11,  8, 11],
         [15, 13, 18,  7]],

        [[ 3, 12, 12, 15],
         [ 8,  6,  6, 12],
         [ 7, 17, 10, 15],
         [ 5,  4,  9,  9]],

        [[ 0,  2, 12,  6],
         [ 8,  2, 10, 14],
         [17,  6, 10, 17],
         [ 5, 15, 17, 12]]],


       [[[ 9,  8, 15,  5],
         [ 9,  4, 12,  9],
         [11,  6,  1, 11],
         [19, 12, 12, 13]],

        [[ 4,  7,  9,  6],
         [15, 11, 18, 16],
         [ 5,  3, 13,  0],
         [ 1, 13,  8, 14]],

        [[13,  9, 10,  0],
         [ 2, 16,  6, 18],
         [ 9,  9, 13, 11],
         [ 1, 14, 16, 16]]]])

In [66]:
a4.shape

(2, 3, 4, 4)

In [70]:
#let us see something about slicing operator which is much common in python.

a4[:1,:2,:2,:2]

array([[[[ 9, 12],
         [14, 15]],

        [[ 3, 12],
         [ 8,  6]]]])

In [1]:
# if you dont have any experience in the slicing operator then it is suggested to see the documentation and 
# then play around those operator to get familiar with the operator.


# Manipulating the numpy arrays

In [2]:
# this section is dealing with the numpy arrays Arithmetic operations.

In [8]:
a1

array([1, 2, 3])

In [10]:
ones=np.ones((2,3))

In [13]:
ones.dtype

#here this is a floting number.

dtype('float64')

In [14]:
#performing addition operation's and sum of the other operation's

a1+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [15]:
a1-ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [16]:
a1*ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [17]:
a1/ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [18]:
a1//ones

#if you are not aware of floor divison please do search on the python documentation, basically it removes the decimal value if it has any
# in our example we did'nt get a decimal so we get the same kind of answer

array([[1., 2., 3.],
       [1., 2., 3.]])

In [19]:
a2/ones

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
arr=np.random.randint(10,size=(2,3))

In [21]:
arr

array([[9, 2, 3],
       [5, 7, 0]])

# Difference between division and floor division

In [22]:
arr/a2

#ahh now we got some decimals so we'll use floor divison 

array([[9.  , 1.  , 1.  ],
       [1.25, 1.4 , 0.  ]])

In [23]:
arr//a2

array([[9, 1, 1],
       [1, 1, 0]])

## Aggregation

In [24]:
sum(a1)

6

In [25]:
a1


array([1, 2, 3])

In [27]:
# The sum() adds the values in a1

In [28]:
np.sum(a1)

#oh the same thing 

6

In [29]:
massive_arr=np.random.random(1000)

#this is the massive array that has more than 1000

In [30]:
massive_arr[:10]

array([0.46544512, 0.53957679, 0.15661534, 0.83031975, 0.90225177,
       0.04716558, 0.89446292, 0.40575934, 0.14049304, 0.15288057])

In [31]:
%timeit sum(massive_arr)

%timeit np.sum(massive_arr)

161 µs ± 7.63 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
10.2 µs ± 44.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
#now see which is faster .....

# Standard Deviation and Variance.

In [3]:
# in this concept i'll suggest you to fo through some of the basic stuffs related to std and Var.

#let us create a array with maximum values and minimum values.

In [4]:
high_var_array=np.array([1,100,200,300,4000,5000])

In [5]:
low_var_array=np.array([2,4,6,8,10])

In [6]:
np.std(low_var_array),np.std(high_var_array)

(2.8284271247461903, 2072.711623024829)

In [7]:
np.var(low_var_array),np.var(high_var_array)

(8.0, 4296133.472222221)

In [8]:
#let's us plot these things.

import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [9]:
plt.hist(low_var_array)
plt.show()

# Dot product.

In [2]:
# we'll see about normal multiplication and the dot product of the matrices.

In [3]:
#let us create two matrices

mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))

In [4]:
mat1

array([[2, 9, 0],
       [3, 5, 1],
       [8, 5, 4],
       [6, 7, 3],
       [6, 4, 1]])

In [5]:
mat2

array([[2, 0, 7],
       [6, 6, 9],
       [6, 2, 5],
       [2, 9, 8],
       [9, 0, 6]])

In [6]:
#let us do the same multiplication

%timeit mat1*mat2

1.14 µs ± 152 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
mat1*mat2

array([[ 4,  0,  0],
       [18, 30,  9],
       [48, 10, 20],
       [12, 63, 24],
       [54,  0,  6]])

In [9]:
# now lets move on to the dot product 

mat3=np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [10]:
# This is need to be highlighted like this not like the above thing we did this is actually

#like multiplying the matrices 

In [ ]:
#google matrix multiplication.

In [11]:
# so taking transpose will give the required matrix.

mat1.T

array([[2, 3, 8, 6, 6],
       [9, 5, 5, 7, 4],
       [0, 1, 4, 3, 1]])

In [12]:
mat3=np.dot(mat1.T,mat2)

In [13]:
mat3

array([[136,  88, 165],
       [128, 103, 213],
       [ 45,  41,  59]])

In [15]:
# here lets try to reshape the matrix

mat1=mat1.reshape((3,5))

In [16]:
mat1

array([[2, 9, 0, 3, 5],
       [1, 8, 5, 4, 6],
       [7, 3, 6, 4, 1]])

mat4=np.dot(mat1,mat2

In [17]:
mat4=np.dot(mat1,mat2)

In [18]:
mat4

array([[109,  81, 149],
       [142,  94, 172],
       [ 85,  66, 144]])

In [19]:
mat1

array([[2, 9, 0, 3, 5],
       [1, 8, 5, 4, 6],
       [7, 3, 6, 4, 1]])

In [20]:
# Reshape may not work as you think so maximum try to transpose the matrix.

# Dot product Example nut butter sales.

In [4]:
np.random.seed()
sales_amount=np.random.randint(20,size=(5,3))
sales_amount

array([[14,  6, 15],
       [ 3,  0, 18],
       [ 8,  8,  4],
       [ 0,  6,  8],
       [15,  7, 16]])

In [6]:
# export the above array as padas dataframe

week_sales=pd.DataFrame(sales_amount,index=['Monday','Tuesday','Wednesday','Thursday','Friday'],
                       columns=['Almond butter','Cashew butter','peanut butter'])
week_sales

Almond butter  Cashew butter  peanut butter
Monday                14              6             15
Tuesday                3              0             18
Wednesday              8              8              4
Thursday               0              6              8
Friday                15              7             16

In [7]:
prices=np.array([10,8,12])

In [11]:
prices.shape

(3,)

In [23]:
butter_price=pd.DataFrame(prices.reshape(3,1), index=['prices'],
                         columns=['Almond butter','Cashew butter','peanut butter'])

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [32]:
#now we need to reshape the array values
prices.reshape(1,3)

array([[10,  8, 12]])

In [29]:
butter_price=pd.DataFrame(prices.reshape(1,3), index=['prices'],
                         columns=['Almond butter','Cashew butter','peanut butter'])

In [31]:
butter_price

Almond butter  Cashew butter  peanut butter
prices             10              8             12

In [33]:
daily_sale=butter_price.dot(week_sales.T)

In [34]:
daily_sale

Monday  Tuesday  Wednesday  Thursday  Friday
prices     368      246        192       144     398

In [35]:
type(daily_sale)

pandas.core.frame.DataFrame

In [36]:
week_sales['Total']=daily_sale.T

In [37]:
week_sales

Almond butter  Cashew butter  peanut butter  Total
Monday                14              6             15    368
Tuesday                3              0             18    246
Wednesday              8              8              4    192
Thursday               0              6              8    144
Friday                15              7             16    398